sequenceDiagram
    participant browser
    participant server

    Note right of the browser: {"content":"spa timee","date":"2024-10-09T07:22:47.099Z"}

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    server-->>browser: {"message":"note created"}
    deactivate server